options {
    directory "/var/cache/bind";
    listen-on port 53 { any; };
    listen-on-v6 port 53 { any; };
    allow-query { any; };
    allow-transfer { any; };
    recursion no;
    auth-nxdomain no;
    dnssec-validation no;
};

controls {
    inet 127.0.0.1 port 953 allow { localhost; } keys { "rndc-key"; };
};

key "rndc-key" {
    algorithm hmac-md5;
    secret "Hw6vD6j7w8k3Zx9j5R2p1N8q4T7y3E6r";
};

key "nsupdate-key" {
    algorithm hmac-sha256;
    secret "K13Tanl014A2QJAaR2nLyqvMwqFClbPPvfTQGIj6X7c=";
};

zone "example.com" IN {
    type master;
    file "/var/lib/bind/db.example.com";
    allow-update { any; };
    allow-transfer { any; };
    notify yes;
};
